- components/Pages/Bootcamps/Hero.tsx
- components/Pages/Bootcamps/HeroCard.tsx
- config/bootcapms/hero-data.json
- pages/javascript-live/index.tsx
- styles/pages/bootcamps/hero-card.scss
- styles/pages/bootcamps/hero.scss
- styles/pages/bootcamps/index.scss
-  Built hero secction.
- ADD testimonials and TransformYourLife sections
> Hero Seccion ( Bootcamps)

- components/Pages/Bootcamps/HeroCard.tsx
- config/bootcapms/hero-data.json
- pages/python-live/index.tsx
- styles/pages/bootcamps/hero-card.scss
> Bootcamps hero

- components/Pages/Bootcamps/MetricCard.tsx
- components/Pages/Bootcamps/Metrics.tsx
- config/bootcamps/metrics.json
- pages/javascript-live/index.tsx
- pages/python-live/index.tsx
- styles/components/bg-video.scss
- styles/pages/bootcamps/hero.scss
- styles/pages/bootcamps/index.scss
- styles/pages/bootcamps/metric-card.scss
- styles/pages/bootcamps/metrics.scss
**Added:**
- **Javascript metrics**
- **Python metrics**
> Metrics Section

- pages/login.tsx
**Fix background into login page**
> add BgVideo component into login page

- components/CarrouselAlliances.tsx
- components/HeroCard.tsx
- components/Pages/Companies/Hero.tsx
- components/Pages/Home/AlliancesKodemia.tsx
- components/Pages/Home/Hero.tsx
- config/navbar-items.json
- pages/empresas.tsx
- styles/components/carrousel-alliances.scss
- styles/pages/companies/hero.scss
- styles/pages/companies/index.scss
- styles/pages/home/alliances-kodemia.scss
- styles/pages/index.scss
- hero
- ADD footer, navbar, carrousel section
-
> Hero company

- components/ExperienceVideo.tsx
- components/Pages/Home/KodemiaExperience.tsx
- config/companies/choose-koder-data.json
- public/icons/btn-close-video.svg
- styles/components/experience-video.scss
**New icon close  on video in Kodemia Experience section**
> Close video button

- components/ApplyForm.tsx
- components/Pages/Home/OurBootcamps.tsx
- config/bootcamps/hero-data-javascript.json
- config/our-bootcamps-cards.json
- stories/OurBootcamps.stories.tsx
- **Python bootcamp no longer shown**
- **Javascript new date**
> :ambulance: fix python bootcamp and js dates

- components/ExperienceVideo.tsx
- components/Pages/Home/KodemiaExperience.tsx
- styles/components/experience-video.scss
- fix video size in experience section
> fix size of video

- components/H3.tsx
- components/TextCursor.tsx
- config/our-bootcamps-cards.json
**Javascript Live new date: 23 de agosto**
> Added new date for next javascript live

- config/bootcamps/hero-data-javascript.json
**Date "26 de julio" no show more in page javascript-live**
> Remove date from javascript-live page

- components/Button.tsx
- components/Footer.tsx
- lib/tracker.ts
- lib/whatsapp.ts
- pages/aplicar/gracias/[bootcamp].tsx
- pages/fin-periodo-de-prueba.tsx
- Adds a whatsapp link creator class to make the use of whatsapp links more clean, reusable and easier to read
- Adds tracking methods to footer links and buttons
- Refactor to button component
> Whatsapp Link Creator

- components/Forms/ApplyLandingForm.tsx
- components/LandingNavbar.tsx
- components/builder/forms/ApplyLandingForm.builder.ts
- components/builder/forms/index.ts
- components/builder/ui/Footer.builder.ts
- components/builder/ui/index.ts
- pages/[...page].tsx
> add components

- components/CardEvent.tsx
- pages/eventos.tsx
- tailwind.config.js
:bug: **title height changed in tablet and laptop**
> Fix title in Event card

- package-lock.json
- package.json
- styles/index.scss
- styles/mixins.scss
- styles/pages/home/testimonial.scss
:recycle:  **Bulma package deleted**
> ➖  Bulma deleted

- components/Pages/Home/OurBootcamps.tsx
- config/our-bootcamps-cards.json
- pages/index.tsx
- Remove backbase banner 
- Remove mobile data
> Remove banner

- config/our-bootcamps-cards.json
- **Date updated to february 14**
> :speech_balloon: New date for Bootcamp JS

- components/Pages/Home/WhatGoingAchieve.tsx
- **Added cursor pointer to slider bar into What Going Achieve section**
> :adhesive_bandage: Fix pointer

- components/Button.tsx
- components/Forms/MobileForm.tsx
- pages/aplicar/backbase/gracias.tsx
- pages/aplicar/backbase/index.tsx
- tailwind.config.js
- **:sparkles: added Backbase Thanyou page**
- **:pencil2: fix typos**
> ✨  Backbase Thankyou page

- config/our-bootcamps-cards.json
- the bootcamp date was updated
> Update the bootcamp date

- pages/mentores.tsx
- :bug: fixed max limit of results in Builder query
- :monocle_face: added log for results in Builder query
- :coffin: remove log for results in mentors query
**Maximized limit of results in Mentors query**
Be sure to add if needed
- Tests
- Types
- Documentation
> 🐛  Fix mentors query

- config/our-bootcamps-cards.json
- ### New date for bootcamp JS updated to may 9
> :speech_balloon: Updated new date for Bootcamp JS

- config/brochure-links.json
- types/common.ts
path: `aplicar/gracias/javascript-live` 
- **Desktop:**
- **Mobile:**
> 🍱 New 2022 brochures
